### ISSUE TITLE
 Error in inicialize Systemair saveconnect #2 

### ISSUE THREAD

**Issue by jezekjkr** [perara/systemair-save-connect#2]
Systemair is not inicialized. Maybe in original homesolutions app(not HACS) in menu Account Settings/Contact Detail is value: null null and there is bug, it is not posible change value null, an error occured ( n is null)

In HACS log:
Integration error.

Logger: homeassistant.config_entries
Source: custom_components/systemair/init.py:98
Integration: Systemair (documentation, issues)
First occurred: 17:16:00 (2 occurrences)
Last logged: 22:36:46

Error setting up entry [jezekjkr@gmail.com](mailto:jezekjkr@gmail.com) for systemair
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/systemair/init.py", line 65, in async_setup_entry
sc_devices = await save_connect_device_setup(hass, api)
File "/config/custom_components/systemair/init.py", line 98, in save_connect_device_setup
sc_devices = await api.get_devices(update=True, fetch_device_info=False)
File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/systemair.py", line 289, in get_devices
devices = await self.graphql.queryGetAccount()
File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/graphql.py", line 167, in queryGetAccount
self.api.data.update_device(device_data=device_data)
File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/data.py", line 18, in update_device
self.devices[device_data["identifier"]] = SaveConnectDevice.parse_obj(
File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
File "pydantic/main.py", line 342, in pydantic.main.BaseModel.init
pydantic.error_wrappers.ValidationError: 1 validation error for SaveConnectDevice
zipcode
value is not a valid integer (type=type_error.integer)

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 17:17:14 (3 occurrences)
Last logged: 22:37:45
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/systemair.py", line 185, in worker
for device in await self.get_devices():
File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/systemair.py", line 289, in get_devices
devices = await self.graphql.queryGetAccount()
File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/graphql.py", line 167, in queryGetAccount
self.api.data.update_device(device_data=device_data)
File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/data.py", line 18, in update_device
self.devices[device_data["identifier"]] = SaveConnectDevice.parse_obj(
File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
File "pydantic/main.py", line 342, in pydantic.main.BaseModel.init
pydantic.error_wrappers.ValidationError: 1 validation error for SaveConnectDevice
zipcode
value is not a valid integer (type=type_error.integer)

**Comment by danielnil** [comment]
Same
