### ISSUE TITLE
this is unfortunatly not working anymore

### ISSUE THREAD

**Issue by Ontrackx** [perara/systemair-save-connect#3]
Logger: homeassistant.config_entries
Source: custom_components/systemair/__init__.py:98
Integration: Systemair ([documentation](https://github.com/perara/systemair-saveconnect), [issues](https://github.com/perara/systemair-saveconnect/issues))
First occurred: 09:16:02 (2 occurrences)
Last logged: 10:17:06

Error setting up entry Systemair for systemair
Error setting up entry ************* for systemair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/systemair/__init__.py", line 65, in async_setup_entry
    sc_devices = await save_connect_device_setup(hass, api)
  File "/config/custom_components/systemair/__init__.py", line 98, in save_connect_device_setup
    sc_devices = await api.get_devices(update=True, fetch_device_info=False)
  File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/systemair.py", line 289, in get_devices
    devices = await self.graphql.queryGetAccount()
  File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/graphql.py", line 156, in queryGetAccount
    response_data = await self.post_request(
  File "/usr/local/lib/python3.10/site-packages/systemair/saveconnect/graphql.py", line 206, in post_request
    response_data = response.json()["data"]
KeyError: 'data'

**Comment by ntguest** [comment]
the same problem

**Comment by mickeblge** [comment]
Same problem for me :(
Any solution in sight?

**Comment by michalkrzempek** [comment]
@perara Could you please let us know If you have plans to fix it?

**Comment by perara** [comment]
I currently have little/no time to fix this issues. It would be awesome if
someone contributed a PR to fix it :)
*Per-Arne Andersen, Ph.D*
Associate Professor
Artificial Intelligence and Cybersecurity, University of Agder
Center for Artificial Intelligence Research (CAIR)
Centre for Integrated Emergency Management (CIEM )
Adviser for SSHF in Artificial Intelligence

+47 905 315 06 <+47+905+315+06> | ***@***.*** | ***@***.***

https://www. <https://www.sysx.no/>per-arne.no
Spikkelia 28 4821 Rykene, Norway
<http://scholar.google.no/citations?user=oPth46oAAAAJ&hl=no>
<http://github.com/perara> <http://www.facebook.com/pereher>
<http://www.linkedin.com/in/perara> <http://twitter.com/PerArneAndersen>
<https://scholar.google.no/citations?user=oPth46oAAAAJ&hl=no>

***@***.***?anonymous&ep=signature>
Reserver
et tidspunkt for å møte meg
***@***.***?anonymous&ep=signature>


man. 30. okt. 2023 kl. 13:34 skrev michalkrzempek ***@***.***
